name: Build containers

permissions:
  contents: read
  packages: write # for publishing containers

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    tags:
      - "v*"

env:
  IMAGE_NAME: trunk
  TRUNK_VERSION: "0.18.8"

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04

    steps:

      - name: Set version
        id: version
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "main" ] && VERSION=latest
          echo "Version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "IMAGE_TAG=$VERSION" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch trunk (amd64)
        run: |
          curl -sSLO https://github.com/trunk-rs/trunk/releases/download/v${TRUNK_VERSION}/trunk-x86_64-unknown-linux-gnu.tar.gz
          tar xavf trunk-x86_64-unknown-linux-gnu.tar.gz
          mkdir -p build/linux/amd64
          chmod a+x trunk
          mv trunk build/linux/amd64/

      - name: Fetch trunk (arm64)
        run: |
          curl -sSLO https://github.com/trunk-rs/trunk/releases/download/v${TRUNK_VERSION}/trunk-aarch64-unknown-linux-gnu.tar.gz
          tar xavf trunk-aarch64-unknown-linux-gnu.tar.gz
          mkdir -p build/linux/arm64
          chmod a+x trunk
          mv trunk build/linux/arm64/

      - run: find build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Containerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=A container to build Rust based WASM frontend applications using `trunk`.
